stages:
 - benchmark
 - publish

sysbench-benchmark:
  image: registry.gitlab.com/tarantool/sysbench
  stage: benchmark
  artifacts:
    paths:
      - result.txt
      - version.txt
  script:
    - ./run-from-docker.sh
  only:
    - triggers

sysbench-publish:
  image: registry.gitlab.com/tarantool/sysbench/result-publication
  stage: publish
  script:
    - cat result.txt
    - cat version.txt
  only:
    - triggers
