stages:
 - benchmark
 - publish

sysbench-benchmark:
  image: ubuntu
  stage: benchmark
  artifacts:
    paths:
      - results.txt
  script:
    - ./run-sysbench.sh

sysbench-publish:
  stage: publish
  script:
   - cat result.txt
#   - python export.py auth.conf result.txt
  only:
   - master
