stages:
 - benchmark
 - sending-email-on-success
 - sending-email-on-failure
 - publish

sysbench-benchmark:
  image: registry.gitlab.com/tarantool/sysbench/benchmarking
  stage: benchmark
  artifacts:
    when: always
    paths:
      - ./benchmarking/result.txt
      - ./benchmarking/version.txt
      - ./benchmarking/commit-author.txt
      - ./benchmarking/last-test.txt
      - ./benchmarking/sysbench-server.log
  script:
    - ./benchmarking/run-from-docker.sh
  tags:
    - sh5
    - tarantool
  only:
    - triggers
    - schedules

sysbench-sending-email-on-failure:
  image: registry.gitlab.com/tarantool/sysbench/sending-email
  stage: sending-email-on-failure
  artifacts:
    when: on_success
    paths:
      - cat letter.txt
  script:
    - ./sending-email/send.sh
  when: on_failure
  tags:
    - gitlab-org
  only:
    - triggers

sysbench-sending-email-on-success:
  image: registry.gitlab.com/tarantool/sysbench/sending-email
  stage: sending-email-on-success
  artifacts:
    when: on_success
    paths:
      - cat letter.txt
  script:
    - SUCCESS_BENCHMARK=1 ./sending-email/send.sh
    - cat letter.txt
  when: on_success
  tags:
    - gitlab-org
  only:
    - triggers

sysbench-publish:
  image: registry.gitlab.com/tarantool/sysbench/publication
  stage: publish
  script:
    - cat ./benchmarking/result.txt
    - cat ./benchmarking/version.txt
    - ./publication/main.py ./benchmarking/result.txt ./benchmarking/version.txt
  tags:
    - gitlab-org
  only:
    - triggers
    - schedules
