stages:
 - benchmark
 - publish

sysbench-benchmark:
  image: registry.gitlab.com/tarantool/sysbench/benchmarking
  stage: benchmark
  artifacts:
    paths:
      - ./benchmarking/result.txt
      - ./benchmarking/version.txt
  script:
    - ./benchmarking/run-from-docker.sh
  only:
    - triggers

sysbench-publish:
  image: registry.gitlab.com/tarantool/sysbench/result-publication
  stage: publish
  script:
    - cat result.txt
    - cat version.txt
    - ./result-publication/main.py result.txt version.txt
  only:
    - triggers
