stages:
 - benchmark
 - publish
 - sending-email

sysbench-benchmark:
  image: registry.gitlab.com/tarantool/sysbench/benchmarking
  stage: benchmark
  artifacts:
    paths:
      - ./benchmarking/result.txt
      - ./benchmarking/version.txt
      - ./benchmarking/commit-author.txt
  script:
    - ./benchmarking/run-from-docker.sh
  tags:
    - sh5
    - tarantool
  only:
    - triggers
    - schedules

sysbench-publish:
  image: registry.gitlab.com/tarantool/sysbench/publication
  stage: publish
  script:
    - cat ./benchmarking/result.txt
    - cat ./benchmarking/version.txt
    - ./publication/main.py ./benchmarking/result.txt ./benchmarking/version.txt
  tags:
    - gitlab-org
  only:
    - triggers
    - schedules

sysbench-sending-email:
  image: registry.gitlab.com/tarantool/sysbench/sending-email
  stage: sending-email
  script:
    - SUCCESS_BENCHMARK=1 ./sending-email/send.sh
  tags:
    - gitlab-org
  only:
    - triggers
