stages:
 - benchmark
 - publish

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

sysbench-benchmark:
  image: ubuntu
  stage: benchmark
  artifacts:
    paths:
      - results.txt
  script:
    - ./run-sysbench.sh

sysbench-publish:
  stage: publish
  script:
   - echo "MOCK push to microb"
#   - python export.py auth.conf result.txt
  only:
   - master
